[default]
GATEWAY_API='API_KEY'
GATEWAY_CRYP='CRYP_KEY'
PAYMENT_GATEWAY_URL='URL_GATEWAY'
SENDGRID_API_KEY='API_KEY'

[development]
DATABASE_URL='DATABASE_URL_IN_DEVELOP'

[testing]
DATABASE_URL="DATABASE_URL_IN_TESTING"
