[tool.poetry]
name = "fast-ecommerce"
version = "0.2.0"
description = "Ecommerce API"
authors = ["Jônatas Oliveira <contato@jonatasoliveira.me>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = "*"
alembic = "*"
sqlalchemy = "*"
databases = {version = "*", extras = ["postgress", "sqlite"]}
passlib = "*"
pyjwt = "*"
python-dotenv = "*"
asyncpg = "*"
aiosqlite = "*"
loguru = "*"
mail-service = "*"
python-jose = {version = "*", extras = ["cryptography"]}
python-multipart = "*"
bcrypt = "*"
beautifulsoup4 = "*"
lxml = "*"
Jinja2 = "*"
sendgrid = "*"
httpx = "*"
pytest-asyncio = "*"
psycopg2-binary = "*"
importlib-metadata = "*"
typing-extensions = "*"
sentry-sdk = "*"
cloudinary = "*"
Pillow = "*"
aiofiles = "*"
boto3 = "*"
zipp = "*"
dynaconf = "*"

[tool.poetry.group.dev.dependencies]
blue = "*"
isort = "*"
ruff = "*"
coverage = "*"
pytest = "*"
ipdb = "*"
pytest-mock = "*"
pytest-cov = "*"
pytest-sugar = "*"
pytest-watch = "*"
pytest-ordering = "*"
pytest-asyncio = "*"

[tool.ruff]
select = ["E", "F", "W", "I", "D", "U", "N", "ERA", "C", "FBT", "B", "A", "T", "I25", "T", "ANN", "YTT", "BLE", "C90", "RUF", "M"]
src = ["src", "tests"]
ignore = ["D203"]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "__init__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.flake8-annotations]
mypy-init-return = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["D104"]

[tool.ruff.isort]
known-first-party = ["src"]
known-third-party = ["fastapi"]

[tool.pylint.main]
ignore = [ "pyproject.toml", "conftest.py" ]

[tool.pylint.master]
extension-pkg-allow-list = ["pydantic", "rapidjson"]

[tool.pylint.refactoring]
# Maximum number of nested blocks for function / method body
max-nested-blocks = 5

[tool.pytest.ini_options]
addopts = ["--strict-markers"]
junit_family= "xunit1"
markers = [
  "smoke: main tests to validate system",
  "integrate: integrate tests",
]

[tool.coverage.run]
omit = [
    "backend/tests/*"
]
[tool.coverage.report]
skip_empty = true

[virtualenvs]
path = ".venv"

[build-system]
requires = ["poetry-core>=1.0.0","setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
