[tool.poetry]
name = "fast-ecommerce"
version = "0.1.0"
description = "Ecommerce API"
authors = ["Jônatas Oliveira <contato@jonatasoliveira.me>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.55.1"
uvicorn = "^0.11.5"
alembic = "^1.4.2"
psycopg2-binary = "^2.8.5"
sqlalchemy = "^1.3.17"
databases = {version = "^0.3.2", extras = ["postgress", "sqlite"]}
autopep8 = "^1.5.3"
pep8 = "^1.7.1"
passlib = "^1.7.2"
pyjwt = "^1.7.1"
python-dotenv = "^0.13.0"
requests = "^2.23.0"
tortoise-orm = "^0.16.13"
asyncpg = "^0.20.1"
aiosqlite = "^0.13.0"
loguru = "^0.5.1"
dynaconf = "^3.0.0"

[tool.poetry.dev-dependencies]
pep8 = "^1.7.1"
jedi = "^0.17.0"
neovim = "^0.3.1"
coverage = "^5.1"
pytest = "^5.4.3"
ipdb = "^0.13.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
