[default]
REDIS_HOST="localhost"
SECRET_KEY="NOT_SECURE_SECRET_KEY"
CONFIRMATION_KEY="NOT_SECURE_CONFIRMATION_KEY"
DATABASE_URL="postgresql://partyoudbuser:partyou123@localhost/ecommerce"
LOG_LEVEL="Debug"
LOG_BACKTRACE=true
